import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContactData } from "./types/contact";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import FloatingButton from "./components/floating-button";
import { getContact } from "./libs/strapi/contact";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
  const contactRaw = await getContact();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="description" content="Estudio de arquitectura enfocado en diseño contemporáneo, paisaje y materialidad." />
        <meta name="robots" content="index, follow" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar contact={contactRaw} />
        {children}
        <Footer contact={contactRaw} />
        <FloatingButton contact={contactRaw}/>

      </body>
    </html>
  );
}
